UI create crud for city
artemlitvenko/CW-service pull request #1
Opened 2021-03-23 15:16 UTC by artemlitvenko

2021-03-23 15:46 UTC, yelyzavetak requested changes

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/actions/city.js
> +import {addCity, removeCity, setCity, updateCity} from "../reducers/cityReducer";
все типы экшенов нужно хранить в файле константы, чтобы не писать строки каждый раз

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/actions/city.js
> +
Зачем так много пустых строк?

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/pages/city/cities/Cities.jsx
> +}
Лучше переписать на:
`const citiesList = useSelector(state => state.cityReducer.cities );

    return (
        <div>
            { citiesList.map(city => <City city={city} setCurrentId={setCurrentId} />) }
        </div>
    );`

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/pages/city/city/City.jsx
> +    function showPopupEditHandler() {
используй стрелочные функции и useCallback

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/pages/city/popupEdit/PopupEdit.jsx
> +    function updateHandler() {
используй стрелочные функции

2021-03-23 15:46 UTC, yelyzavetak commented on client/src/reducers/cityReducer.js
> +});
Тоже вынести с отдельный файл

2021-03-23 15:46 UTC, yelyzavetak commented on client/package.json
> +  "proxy": "http://localhost:5000",
Зачем

2021-03-24 10:29 UTC, artemlitvenko commented on client/package.json
> +  "proxy": "http://localhost:5000",
была ошибка Cors, решал ее и забыл убрать

2021-03-24 11:16 UTC, yelyzavetak approved these changes

2021-03-24 11:59 UTC, merged