Create dashboard with calendar
artemlitvenko/CW-service pull request #12
Opened 2021-06-08 14:07 UTC by artemlitvenko

2021-06-09 06:24 UTC, yelyzavetak requested changes

2021-06-09 06:24 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/calendar/Calendar.jsx
> +    moment.updateLocale('en', { week: { dow: 1 } });
наверное это тоже лучше в юз эффект, чтобы не вызывать функцию каждый раз при ререндере

2021-06-09 06:24 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/calendar/Calendar.jsx
> +    const startDay = today.clone().startOf('month').startOf('week');
используй тут и ниже useMemo && useCallback

2021-06-09 06:24 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/calendarBody/CalendarBody.jsx
> +    const totalDays = daysOfGrid;
используй тут и ниже useMemo && useCallback

2021-06-09 06:24 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/orderInCell/OrderInCell.jsx
> +                    <div>{order.start_time.slice(11, 16)}</div>
это зачем?

2021-06-09 08:47 UTC, artemlitvenko commented on client/src/pages/dashboard/calendar/orderInCell/OrderInCell.jsx
> +                    <div>{order.start_time.slice(11, 16)}</div>
Это проверка есть ли в этот день order и нужно ли его отрисовывать

2021-06-09 10:25 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/orderInCell/OrderInCell.jsx
> +                    <div>{order.start_time.slice(11, 16)}</div>
я про слайс, зачем он тут?

2021-06-09 10:46 UTC, artemlitvenko commented on client/src/pages/dashboard/calendar/orderInCell/OrderInCell.jsx
> +                    <div>{order.start_time.slice(11, 16)}</div>
обрезал дату, чтобы лишнее убрать

2021-06-09 10:48 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/orderInCell/OrderInCell.jsx
> +                    <div>{order.start_time.slice(11, 16)}</div>
https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/

2021-06-10 06:08 UTC, yelyzavetak requested changes

2021-06-10 06:08 UTC, yelyzavetak commented on client/src/pages/dashboard/calendar/calendar/Calendar.jsx
> +    }, [moment.updateLocale('en', { week: { dow: 1 } })]);
а зачем тут нужна зависимость? Достаточно же на маунт это сделать и все, или нет?

2021-06-10 06:13 UTC, yelyzavetak approved these changes

2021-06-10 06:18 UTC, merged